add arm64 support
hansmi/prometheus-paperless-exporter pull request #32
Opened 2024-09-21 23:22 UTC by simono41

Since I use a VM with arm64 architecture and wanted to use this Prometheus exporter, I expanded the .goreleaser.yml to include arm64 support. The build worked so far, but you need to test it to see if you can upload the images here correctly.

2024-09-22 18:01 UTC, hansmi requested changes
Thank you for your proposal. Please let me know if you can/want to address the comments, otherwise I can take care of that.

2024-09-22 18:01 UTC, hansmi commented on .goreleaser.yml
> +    goarch:
Per https://go.dev/wiki/PortingPolicy#first-class-ports `linux/arm64` is part of the first-class ports (via https://go.dev/wiki/PortingPolicy#first-class-ports). Setting `goos` and `goarch` should not be necessary and, without having checked in detail now, may even be disadvantageous (other targets are dropped).

2024-09-22 18:01 UTC, hansmi commented on .goreleaser.yml
> +    extra_files:
Just picking one example. YAML supports reusing values using aliases (`&foo`, `*foo`) and multiple mapping entries (`<<: *foo`). Unfortunately not for partial lists. At least the completely equivalent settings can be aliased.

https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html

2024-09-22 18:46 UTC, simono41 commented on .goreleaser.yml
> +    goarch:
You're right it's probably redundant because they already build arm64 compiled binaries, but unfortunately there's no Docker image build for it yet.

2024-09-22 18:49 UTC, simono41 commented on .goreleaser.yml
> +    extra_files:
True, I didn't even think of that. If possible then you can do it that way. I was just playing around so I can build a local arm64 image with goreleaser.

2024-10-13 21:59 UTC, hansmi commented
@simono41, thank you once again for your proposal here. Getting everything to work through GitHub actions required installing QEMU, but otherwise your config was almost there (modulo the bits removing builds).

Release 0.0.5 now has a Linux/arm64 build.

2024-10-13 21:59 UTC, closed without merging